
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "cas-new-1_ca_chains" {
  description = "The CA chains in PEM format."
  value       = module.cas-new-1.ca_chains
}
output "cas-new-1_ca_ids" {
  description = "The CA ids."
  value       = module.cas-new-1.ca_ids
}
output "cas-new-1_ca_pool" {
  description = "The CA pool resource."
  value       = module.cas-new-1.ca_pool
}
output "cas-new-1_ca_pool_id" {
  description = "The FULL ID of the CA Pool for the SWP."
  value       = module.cas-new-1.ca_pool_id
}
output "cas-new-1_ca_pool_name" {
  description = "CA pool name"
  value       = module.cas-new-1.ca_pool_name
}
output "cas-new-1_cas" {
  description = "The Certificate Authority resources."
  value       = module.cas-new-1.cas
}
output "cas-new-1_ca_roots" {
  description = "The root CA certificates in PEM format, concatenated with newlines."
  value       = module.cas-new-1.ca_roots
}
output "vpc-1_network" {
  description = "The created network"
  value       = module.vpc-1.network
}
output "vpc-1_network_id" {
  description = "The ID of the VPC being created"
  value       = module.vpc-1.network_id
}
output "vpc-1_network_name" {
  description = "The name of the VPC being created"
  value       = module.vpc-1.network_name
}
output "vpc-1_network_self_link" {
  description = "The URI of the VPC being created"
  value       = module.vpc-1.network_self_link
}
output "vpc-1_project_id" {
  description = "VPC project id"
  value       = module.vpc-1.project_id
}
output "vpc-1_route_names" {
  description = "The route names associated with this VPC"
  value       = module.vpc-1.route_names
}
output "vpc-1_subnets" {
  description = "A map with keys of form subnet_region/subnet_name and values being the outputs of the google_compute_subnetwork resources used to create corresponding subnets."
  value       = module.vpc-1.subnets
}
output "vpc-1_subnets_flow_logs" {
  description = "Whether the subnets will have VPC flow logs enabled"
  value       = module.vpc-1.subnets_flow_logs
}
output "vpc-1_subnets_ids" {
  description = "The IDs of the subnets being created"
  value       = module.vpc-1.subnets_ids
}
output "vpc-1_subnets_ips" {
  description = "The IPs and CIDRs of the subnets being created"
  value       = module.vpc-1.subnets_ips
}
output "vpc-1_subnets_by_region_purpose" {
  description = "A list of subnet summary objects containing id, purpose, and region extracted from the subnets map."
  value       = module.vpc-1.subnets_by_region_purpose
}
output "vpc-1_subnets_names" {
  description = "The names of the subnets being created"
  value       = module.vpc-1.subnets_names
}
output "vpc-1_subnets_private_access" {
  description = "Whether the subnets will have access to Google API's without a public IP"
  value       = module.vpc-1.subnets_private_access
}
output "vpc-1_subnets_regions" {
  description = "The region where the subnets will be created"
  value       = module.vpc-1.subnets_regions
}
output "vpc-1_subnets_secondary_ranges" {
  description = "The secondary ranges associated with these subnets"
  value       = module.vpc-1.subnets_secondary_ranges
}
output "vpc-1_subnets_self_links" {
  description = "The self-links of subnets being created"
  value       = module.vpc-1.subnets_self_links
}
output "internal-load-balancer-1_forwarding_rule" {
  description = "The forwarding rule self_link."
  value       = module.internal-load-balancer-1.forwarding_rule
}
output "internal-load-balancer-1_forwarding_rule_id" {
  description = "The forwarding rule id."
  value       = module.internal-load-balancer-1.forwarding_rule_id
}
output "internal-load-balancer-1_ip_address" {
  description = "The internal IP assigned to the regional forwarding rule."
  value       = module.internal-load-balancer-1.ip_address
}
output "routes-1_route_ids" {
  description = "The IDs of the created routes."
  value       = module.routes-1.route_ids
}
output "routes-1_route_names" {
  description = "The names of the created routes."
  value       = module.routes-1.route_names
}
output "routes-1_routes" {
  description = "The created routes resources"
  value       = module.routes-1.routes
}
output "psci-compute-template-1_network_interface_details" {
  description = "The names and VLAN tags of the template interfaces."
  value       = module.psci-compute-template-1.network_interface_details
}
output "test-swp2-2_gateway_id" {
  description = "Identifier for the secure web proxy gateway."
  value       = module.test-swp2-2.gateway_id
}
output "test-swp2-2_gateway_ip_addresses" {
  description = "The IP addresses assigned to the Secure Web Proxy gateway."
  value       = module.test-swp2-2.gateway_ip_addresses
}
output "test-swp2-2_network" {
  description = "The VPC network associated with the gateway."
  value       = module.test-swp2-2.network
}
output "test-swp2-2_policy_id" {
  description = "Identifier of the secure web proxy gateway policy."
  value       = module.test-swp2-2.policy_id
}
output "test-swp2-2_ports" {
  description = "Ports of the secure web proxy resource created."
  value       = module.test-swp2-2.ports
}
output "test-swp2-2_project_id" {
  description = "The project ID where the Secure Web Proxy is deployed."
  value       = module.test-swp2-2.project_id
}
output "test-swp2-2_rule_ids" {
  description = "Identifiers of the secure web proxy rules created."
  value       = module.test-swp2-2.rule_ids
}
output "test-swp2-2_self_link" {
  description = "The URI of the created resource."
  value       = module.test-swp2-2.self_link
}
output "test-swp2-2_server_tls_policy_id" {
  description = "The unique identifier of the Server TLS Policy."
  value       = module.test-swp2-2.server_tls_policy_id
}
output "test-swp2-2_service_attachment_id" {
  description = "ID of the service attachment resource, if created."
  value       = module.test-swp2-2.service_attachment_id
}
output "test-swp2-2_subnetwork" {
  description = "The specific subnetwork used by the gateway."
  value       = module.test-swp2-2.subnetwork
}
output "test-swp2-2_url_list_ids" {
  description = "Identifiers of the secure web proxy url lists."
  value       = module.test-swp2-2.url_list_ids
}
output "test-swp2-3_gateway_id" {
  description = "Identifier for the secure web proxy gateway."
  value       = module.test-swp2-3.gateway_id
}
output "test-swp2-3_gateway_ip_addresses" {
  description = "The IP addresses assigned to the Secure Web Proxy gateway."
  value       = module.test-swp2-3.gateway_ip_addresses
}
output "test-swp2-3_network" {
  description = "The VPC network associated with the gateway."
  value       = module.test-swp2-3.network
}
output "test-swp2-3_policy_id" {
  description = "Identifier of the secure web proxy gateway policy."
  value       = module.test-swp2-3.policy_id
}
output "test-swp2-3_ports" {
  description = "Ports of the secure web proxy resource created."
  value       = module.test-swp2-3.ports
}
output "test-swp2-3_project_id" {
  description = "The project ID where the Secure Web Proxy is deployed."
  value       = module.test-swp2-3.project_id
}
output "test-swp2-3_rule_ids" {
  description = "Identifiers of the secure web proxy rules created."
  value       = module.test-swp2-3.rule_ids
}
output "test-swp2-3_self_link" {
  description = "The URI of the created resource."
  value       = module.test-swp2-3.self_link
}
output "test-swp2-3_server_tls_policy_id" {
  description = "The unique identifier of the Server TLS Policy."
  value       = module.test-swp2-3.server_tls_policy_id
}
output "test-swp2-3_service_attachment_id" {
  description = "ID of the service attachment resource, if created."
  value       = module.test-swp2-3.service_attachment_id
}
output "test-swp2-3_subnetwork" {
  description = "The specific subnetwork used by the gateway."
  value       = module.test-swp2-3.subnetwork
}
output "test-swp2-3_url_list_ids" {
  description = "Identifiers of the secure web proxy url lists."
  value       = module.test-swp2-3.url_list_ids
}
