
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

variable "region" {
  description = "Region for cloud resources."
  type = string
  default = "us-central1"
}
variable "tenant_project_id" {
  type = string
}
variable "location" {
  type = string
  default = "us-central1"
}
