
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "authz-policy-and-extension-2_extension_ids" {
  description = "Map of extension names to their unique resource IDs."
  value       = module.authz-policy-and-extension-2.extension_ids
}
output "authz-policy-and-extension-2_policy_extension_map" {
  description = "Maps each policy name to its single assigned extension ID."
  value       = module.authz-policy-and-extension-2.policy_extension_map
}
output "authz-policy-and-extension-2_policy_ids" {
  description = "Map of policy names to their unique resource IDs."
  value       = module.authz-policy-and-extension-2.policy_ids
}
