
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

locals {
  authz_config      = jsondecode(var.authz_policy_and_extension_config_json)
  extension_configs = [for k, v in local.authz_config : v]
  policy_configs    = [for k, v in local.authz_config : jsondecode(k)]
}

module "authz-policy-and-extension-2" {
  source            = "github.com/vandnagarggoogle/terraform-google-policy-authz-extension?ref=v0.0.21"
  project_id        = var.tenant_project_id
  location          = var.authz-policy-and-extension-2_location
  extensions_config = local.extension_configs
  policies_config   = local.policy_configs
}
