
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

variable "tenant_project_id" {
  type = string
}
variable "authz-policy-and-extension-2_location" {
  type = string
  default = "us-central1"
}



variable "authz_policy_and_extension_config_json" {
  type = string
}
