
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

region     = "us-central1"
project_id = "singhalbhaskar-dev-4"
location   = "us-central1"
