
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "agent-gateway-1_agent_gateway_id" {
  description = "The full resource ID of the Agent Gateway."
  value       = module.agent-gateway-1.agent_gateway_id
}
output "agent-gateway-1_mtls_endpoint" {
  description = "The mTLS Endpoint associated with this Agent Gateway for agent connections."
  value       = module.agent-gateway-1.mtls_endpoint
}
