
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "cas-new-1" {
  source     = "github.com/vandnagarggoogle/terraform-google-cas?ref=v1.0.20"
  project_id = var.tenant_project_id
  location   = var.location
  ca_pool_config = {
    create_pool = {
      enterprise_tier = false
      name            = "uk1-18feb-ca"
    }
  }
  ca_configs = {
    uk1-18feb-caroot = {
      deletion_protection                    = false
      ignore_active_certificates_on_deletion = false
      is_ca                                  = true
      key_spec = {
        algorithm = "RSA_PKCS1_2048_SHA256"
      }
      key_usage = {
        cert_sign          = true
        client_auth        = false
        code_signing       = false
        content_commitment = false
        crl_sign           = true
        data_encipherment  = false
        decipher_only      = false
        digital_signature  = false
        email_protection   = false
        encipher_only      = false
        key_agreement      = false
        key_encipherment   = true
        ocsp_signing       = false
        server_auth        = true
        time_stamping      = false
      }
      skip_grace_period = true
      subject = {
        common_name  = "uk1-18feb-cn"
        organization = "Google"
      }
    }
  }
}
module "vpc-1" {
  source                                    = "github.com/Daisyprakash/terraform-google-network?ref=v15.2.1"
  project_id                                = var.tenant_project_id
  network_name                              = "uk1-18feb-vpc"
  subnets                                   = [{"subnet_region" = "us-central1", "purpose" = "PRIVATE", "role" = "ACTIVE", "subnet_ip" = "10.0.0.0/24", "subnet_name" = "uk1-18feb-s0"}, {"subnet_region" = "us-central1", "purpose" = "REGIONAL_MANAGED_PROXY", "role" = "ACTIVE", "subnet_ip" = "10.0.1.0/24", "subnet_name" = "uk1-18feb-s1"}, {"subnet_name" = "uk1-18feb-s2", "subnet_region" = "us-central1", "purpose" = "PRIVATE_SERVICE_CONNECT", "role" = "ACTIVE", "subnet_ip" = "10.0.2.0/24"}]
  network_firewall_policy_enforcement_order = "BEFORE_CLASSIC_FIREWALL"
}
module "internal-load-balancer-1" {
  source     = "github.com/vandnagarggoogle/terraform-google-lb-internal?ref=v1.0.19"
  project_id = var.tenant_project_id
  region     = var.region
  network    = module.vpc-1.network_name
  subnetwork = module.vpc-1.subnets_names[0]
  name       = "uk1-18feb-ilb"
  backends = [{
    group = module.ce-mig-1.instance_group
  }]
  health_check = {
    enable_log = false
    port       = 80
    type       = "http"
  }
  source_ip_ranges = [module.vpc-1.subnets_ips[1]]
  depends_on = [module.vpc-1]
}
module "routes-1" {
  source       = "github.com/vandnagarggoogle/terraform-google-network//modules/routes?ref=v1.0.6"
  project_id   = var.tenant_project_id
  network_name = module.vpc-1.network_name
  routes       = [{"destination_range" = "10.50.0.0/16", "name" = "uk1-18feb-route", "next_hop_ilb" = module.internal-load-balancer-1.forwarding_rule_id, "next_hop_internet" = false, "priority" = 1000}]
}
module "ce-mig-1" {
  source            = "github.com/terraform-google-modules/terraform-google-vm//modules/mig?ref=v13.6.1"
  project_id        = var.tenant_project_id
  region            = var.region
  mig_name          = "uk1-18feb-mig"
  instance_template = module.psci-compute-template-1.self_link
}
module "psci-compute-template-1" {
  source                 = "github.com/vandnagarggoogle/terraform-google-vm//modules/instance_template?ref=v0.0.7"
  project_id             = var.tenant_project_id
  region                 = var.region
  source_image           = "rocky-linux-9-optimized-gcp-v20260213"
  source_image_family    = "rocky-linux-9-optimized-gcp"
  source_image_project   = "gce-staging-images"
  name_prefix            = "psci-18feb"
  network                = module.vpc-1.network_name
  subnetwork             = module.vpc-1.subnets_names[0]
  subnetwork_project     = module.vpc-1.project_id
  create_service_account = false
  access_config          = [{"nat_ip" = null, "network_tier" = "PREMIUM"}]
}
module "test-swp2-2" {
  source       = "github.com/Daisyprakash/terraform-google-secure-web-proxy?ref=v1.0.10"
  project_id   = var.tenant_project_id
  gateway_name = "unitkind1-swp-tls"
  region       = var.region
  network      = module.vpc-1.network_id
  subnets      = module.vpc-1.subnets_by_region_purpose
  # service_attachment = {
  #   name = "unitkind1-swp-sa2"
  #   automatic_accept_all_connections = true
  # }
  policy = {
    name = "unitkind1-swp-tls-policy"
  #   tls_inspection_policy = {
  #     ca_pool = module.cas-new-1.ca_pool_id
  #     name    = "unitkind1-swp-tls-inspec-policy"
  #   }
  }
  rules = {
    "allow": {
      basic_profile   = "ALLOW"
      priority = 1000
      session_matcher         = "true"
    }
  }
}
module "test-swp2-3" {
  source       = "github.com/Daisyprakash/terraform-google-secure-web-proxy?ref=v1.0.10"
  project_id   = var.tenant_project_id
  gateway_name = "unitkind1-swp-mtls"
  region       = var.region
  service_attachment = {
    name = "unitkind1-swp-mtls-psc-sa"
    automatic_accept_all_connections = true
  }
  network = module.vpc-1.network_id
  subnets = module.vpc-1.subnets_by_region_purpose
  policy = {
    name = "unitkind1-swp-mtls-policy"
  }
  # server_tls_policy_config = {
  #   allow_open = true
  #   name       = "unitkind1-swp-server-tls-policy"
  # }
  rules = {
    "allow": {
      basic_profile   = "ALLOW"
      priority = 1000
      session_matcher         = "true"
    }
  }
}
